# mysql-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rootpass"
        - name: MYSQL_DATABASE
          value: "carrental"
        - name: MYSQL_USER
          value: "user"
        - name: MYSQL_PASSWORD
          value: "userpass"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
---
# mysql-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
# web-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: carrental-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carrental-web
  template:
    metadata:
      labels:
        app: carrental-web
    spec:
      containers:
      - name: web
        image: roughrover/carrental-app:latest
        ports:
        - containerPort: 80
---
# phpmyadmin-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        env:
        - name: PMA_HOST
          value: mysql
        - name: MYSQL_ROOT_PASSWORD
          value: rootpass
        ports:
        - containerPort: 80
---
# services.yaml
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
  clusterIP: None  # Headless service for DB
---
apiVersion: v1
kind: Service
metadata:
  name: carrental-service
spec:
  type: NodePort
  selector:
    app: carrental-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
spec:
  type: NodePort
  selector:
    app: phpmyadmin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30008
